import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // ── Original design tokens (CSS-var based, used by non-home pages) ──
        bg:            'var(--color-bg)',
        surface:       'var(--color-surface)',
        subtle:        'var(--color-subtle)',
        text:          'var(--color-text)',
        'text-muted':  'var(--color-text-muted)',
        'text-faint':  'var(--color-text-faint)',
        accent:        'var(--color-accent)',
        'accent-dark': 'var(--color-accent-dark)',
        'accent-soft': 'var(--color-accent-soft)',
        border:        'var(--color-border)',
        'border-dark': 'var(--color-border-dark)',
        success:       'var(--color-success)',
        error:         'var(--color-error)',

        // ── Stitch homepage red theme (hardcoded hex) ──
        'primary':                   '#b7102a',
        'on-primary':                '#ffffff',
        'primary-container':         '#db313f',
        'primary-fixed':             '#ffdad8',
        'primary-fixed-dim':         '#ffb3b1',
        'on-primary-fixed':          '#410007',
        'on-primary-fixed-variant':  '#92001c',
        'secondary':                 '#485f84',
        'on-secondary':              '#ffffff',
        'secondary-container':       '#bbd3fd',
        'secondary-fixed':           '#d5e3ff',
        'secondary-fixed-dim':       '#b0c7f1',
        'on-secondary-fixed':        '#001b3c',
        'on-secondary-fixed-variant':'#30476a',
        'on-secondary-container':    '#445a7f',
        'tertiary':                  '#286182',
        'on-tertiary':               '#ffffff',
        'tertiary-container':        '#447a9c',
        'tertiary-fixed':            '#c7e7ff',
        'tertiary-fixed-dim':        '#98cdf2',
        'on-tertiary-fixed':         '#001e2e',
        'on-tertiary-fixed-variant': '#064c6b',
        'on-tertiary-container':     '#fcfcff',
        'background':                '#fff8f7',
        'on-background':             '#271717',
        'surface-dim':               '#f1d3d2',
        'surface-bright':            '#fff8f7',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#fff0ef',
        'surface-container':         '#ffe9e8',
        'surface-container-high':    '#ffe1e0',
        'surface-container-highest': '#f9dcda',
        'surface-variant':           '#f9dcda',
        'on-surface':                '#271717',
        'on-surface-variant':        '#5b403f',
        'outline':                   '#8f6f6e',
        'outline-variant':           '#e4bebc',
        'inverse-surface':           '#3e2c2b',
        'inverse-on-surface':        '#ffedeb',
        'inverse-primary':           '#ffb3b1',
        'on-error-container':        '#93000a',
        'error-container':           '#ffdad6',
        'surface-tint':              '#bb152c',
        'data-blue':                 '#00B4FF',
        'soft-teal':                 '#77C1C1',
        'alvis-red':                 '#e63946',
        'border-glass':              'rgba(255,255,255,0.2)',
        'surface-glass':             'rgba(255,255,255,0.7)',
      },
      fontFamily: {
        display: ['var(--font-display)', 'sans-serif'],
        body:    ['var(--font-body)', 'sans-serif'],
        mono:    ['var(--font-mono)', 'monospace'],
        // Stitch aliases (map to same underlying vars)
        'display-lg':  ['var(--font-display)', 'sans-serif'],
        'headline-md': ['var(--font-display)', 'sans-serif'],
        'headline-xl': ['var(--font-display)', 'sans-serif'],
        'label-caps':  ['var(--font-display)', 'sans-serif'],
        'body-lg':     ['var(--font-body)', 'sans-serif'],
        'body-md':     ['var(--font-body)', 'sans-serif'],
      },
      fontSize: {
        'display-2xl': ['clamp(3rem, 8vw, 6rem)',     { lineHeight: '1.0',  letterSpacing: '-0.03em' }],
        'display-xl':  ['clamp(2.5rem, 6vw, 4.5rem)', { lineHeight: '1.05', letterSpacing: '-0.025em' }],
        'display-lg':  ['clamp(2rem, 4vw, 3.5rem)',   { lineHeight: '1.1',  letterSpacing: '-0.02em' }],
        'display-md':  ['clamp(1.5rem, 3vw, 2.5rem)', { lineHeight: '1.2',  letterSpacing: '-0.015em' }],
        'body-lg':     ['1.125rem', { lineHeight: '1.7' }],
        'body-md':     ['1rem',     { lineHeight: '1.6' }],
        'body-sm':     ['0.875rem', { lineHeight: '1.5' }],
        'label':       ['0.75rem',  { lineHeight: '1', letterSpacing: '0.1em' }],
        // Stitch additions
        'headline-xl':       ['48px',  { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl-mobile':['32px',  { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md':       ['32px',  { lineHeight: '1.3', fontWeight: '600' }],
        'label-caps':        ['12px',  { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '700' }],
      },
      spacing: {
        'section-gap':    '160px',
        'margin-mobile':  '20px',
        'gutter':         '32px',
        'container-max':  '1280px',
      },
      maxWidth: {
        '8xl':           '88rem',
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}

export default config
